### PR TITLE
Halve the rotation exponents, fix a bug where negative rotation value…

### LINKED ISSUE #48: Undocumented behavior from WPILib
The `RobotDrive` class in WPILib squares rotation by default. This isn't in any of the documentation but if you can find it in the source code of the the `arcadeDrive` method that is used in our `Drivetrain` class.
```
   490	  public void arcadeDrive(double moveValue, double rotateValue) {
   491	    this.arcadeDrive(moveValue, rotateValue, true);
   492	  }
```
The boolean argument in that method call is for whether or not rotation should be squared. WPILib has been making it so that our rotation exponents have always been 2 times what they were supposed to be all along.

### PR DESCRIPTION
**Pull request by J0hnCena**
…s cannot be rooted. This closes #48

### CODE REVIEW

**Comment by LoadingPleaseWait** [comment]
Can you add something in the documentation for this?

File: src/org/impact2585/lib2585/Drivetrain.java [hunk 1]
```diff
@@ -53,7 +74,15 @@ public RobotDrive getDrivetrain() {
 	public void setDrivetrain(RobotDrive drivetrain) {
 		this.drivetrain = drivetrain;
 	}
-
+	
+	/**Controls the movement of the drivetrain with no inverting or different rotation exponents
+	 * @param desiredRampForward
```
Comment (LoadingPleaseWait) [inline src/org/impact2585/lib2585/Drivetrain.java]: You should still add a description for each parameter.
